name: Lint and Test

on:
  push:
    branches-ignore:
      - main
      - gh-pages
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: chartboost/ruff-action@v1

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', '3.9' ]
    name: Test python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run pytest
        run: pytest --cov-fail-under=35
